[build]
command = "pnpm run build"
publish = "dist/"

[[redirects]]
from = "/*"
to = "/.netlify/functions/astro"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
