[build]
command = "pnpm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/.netlify/functions-internal/entry"
status = 200

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
